// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF1y7BYWdG7mlLLLVuuU2C9Fa1crnU-nY',
    appId: '1:1040055424891:web:d802d7554d5a018187cfde',
    messagingSenderId: '1040055424891',
    projectId: 'utc2-edu-vn',
    authDomain: 'utc2-edu-vn.firebaseapp.com',
    storageBucket: 'utc2-edu-vn.firebasestorage.app',
    measurementId: 'G-SNE59PC26S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlUZaIXgD5eXTmPUt-kR1cgVoqS3ECB3Q',
    appId: '1:1040055424891:android:10a99849f331dd4787cfde',
    messagingSenderId: '1040055424891',
    projectId: 'utc2-edu-vn',
    storageBucket: 'utc2-edu-vn.firebasestorage.app',
  );

}